{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "medvision.secretName" . }}
  labels:
    {{- include "medvision.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
{{- end }}
